<div class="row">
    <div class="col col-sm-2 list">
        <div id="auto-manager-sidebar" class="list-group">
            <a class="list-group-item fa fa-plus" href="/auto/manager/new/manufacturer">
                Manufacturer
            </a>
            <a class="list-group-item fa fa-plus" href="/auto/manager/new/model">
                Model
            </a>
            <a class="list-group-item fa fa-plus" href="/auto/manager/new/vehicle">
                Vehicle
            </a>
        </div>
    </div>
    <div id="manager-form" class="col col-lg-6">
        form col
    </div>
</div>