<?php

declare(strict_types=1);

//$path = $this->url();
$this->headLink()
    ->appendStylesheet('/assets/css/bootstrap.min.css')
    ->appendStylesheet('https://use.fontawesome.com/releases/v5.13.0/css/all.css')
    ->appendStylesheet('/assets/css/style.css');

$this->inlineScript()
    ->appendFile('https://cdn.jsdelivr.net/npm/jquery@3.7.0/dist/jquery.js')
    //->appendFile('/assets/js/bootstrap.min.js')
    ->appendFile('https://unpkg.com/@popperjs/core@2')
    //->appendFile('/assets/js/bootstrap.min.js')
    ->appendFile('/assets/js/pubsub.js')
    ->appendFile('/assets/js/app.js');
?>
<!DOCTYPE html>
<html lang="en" class="h-100" data-bs-theme="dark">
<head>
    <base href="/" />
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="shortcut icon" href="/assets/img/favicon.ico" />
    <?=$this->headTitle('AutoManager')->setSeparator(' - ')->setAutoEscape(false)?>
    <?=$this->headMeta()?>
    <?=$this->headLink()?>
</head>
<body class="d-flex flex-column h-100 app">
    <header class="app-header">
        <nav class="navbar navbar-expand-sm fixed-top phpurple" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="#navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <!-- Brand -->
                    <a class="navbar-brand" href="<?=$this->url('home')?>">
                        <img src="/assets/img/webinertia-logo-75.png" alt="Webinertia Mezzio" />
                    </a>
                </div>
                <!-- Links -->
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a href="<?=$this->url('home')?>"
                               class="nav-link<?=$this->url() === $this->url('home') ? ' active' : ''?>">
                                <i class="fa fa-home"></i> Home
                            </a>
                        </li>
                        <li>
                            <a href="<?=$this->url('auto-manager')?>"
                               class="nav-link<?=$this->url() === $this->url('auto-manager') ? ' active' : ''?>">
                                <i class="fa fa-car"></i> Auto Manager
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="https://docs.mezzio.dev/mezzio" target="_blank" class="nav-link">
                                <i class="fa fa-book"></i> Docs
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="https://github.com/Tyrsson/automanager" target="_blank" class="nav-link">
                                <i class="fa fa-wrench"></i> Contribute
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="<?=$this->url('api.ping')?>" class="nav-link">
                                <i class="fa fa-network-wired"></i> Ping
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main class="flex-shrink-0 app-content">
        <section id="app-workspace" class="container p-5">
            <?=$this->content?>
        </section>
    </main>
    <footer class="mt-auto app-footer">
        <div class="container">
            <hr />
            <p>
                &copy; <?=date('Y')?> <a href="https://github.com/orgs/Tyrsson/automanager">AutoManager</a>
            </p>
        </div>
    </footer>
    <?=$this->inlineScript()?>
</body>
</html>
